nclude: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_single_quotes

analyzer:
  errors:
    omit_local_variable_types: ignore

formatter:
  trailing_commas: preserve
