name: bonsoir_platform_interface
description: Common platform interface for the Bonsoir plugin.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_platform_interface
version: 6.0.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.10.0 <2.0.0"
  plugin_platform_interface: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0
