name: bonsoir_example
description: Demonstrates how to use the bonsoir plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
resolution: workspace

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bonsoir:
    path:
      ../
  flutter_riverpod: ^2.6.1
  device_info_plus: ^11.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
